addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "4.1.1")
addSbtPlugin("com.typesafe"      % "sbt-mima-plugin"     % "0.8.1")
addSbtPlugin("org.foundweekends" % "sbt-bintray"         % "0.6.1")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.7.6")
